function notTheSame =  compareConfig(config1, config2)
% Comparing two config struct variables
    if (config1.Model.club_membership_cost ~= config2.Model.club_membership_cost) || ...
            (~(strcmp(config1.Model.club_congestion_function,...
            config2.Model.club_congestion_function))) ...
            || (~(strcmp(config1.Model.individual_congestion_function,...
            config2.Model.individual_congestion_function))) || ...
            (config1.Environment.number_of_agents ~= ...
            config2.Environment.number_of_agents)
        notTheSame = true;
        return
    end
    if(strcmp(config1.Model.club_congestion_function,'exponential'))
        if (config1.Model.club_congestion_delta ~=...
                config2.Model.club_congestion_delta) ||...
                (config1.Model.club_congestion_a ~= ...
                config2.Model.club_congestion_a)
            notTheSame = true;
            return
        end    
    end
    if(strcmp(config1.Model.individual_congestion_function,'exponential'))
        if (config1.Model.individual_congestion_delta ~=...
                config2.Model.individual_congestion_delta) ||...
                (config1.Model.individual_congestion_a ~= ...
                config2.Model.individual_congestion_a)
            notTheSame = true;
            return
        end    
    end        
    notTheSame = false;
end    
    