function config = getConfigurations(config)
    % config = getConfigurations(config)
    %
    % This function changes 'config' so that in each field it will contain
    % only the value as configured by the user.
    
    fieldStrArr = {...
    'config.Model.club_membership_cost',...
    'config.Model.club_congestion_function',...
    'config.Model.club_congestion_delta',...
    'config.Model.club_congestion_a',...
    'config.Model.individual_congestion_function',...
    'config.Model.individual_congestion_delta',...
    'config.Model.individual_congestion_a',...
    'config.Model.geodesic_distance',...
    'config.Environment.number_of_agents',...
    'config.Environment.number_of_clubs',...
    'config.Processing.processing_type',...
        'config.Processing.clubwise_stability'};
nFields = length(fieldStrArr);
for iField = 1:nFields
    fieldName = fieldStrArr{iField};
    value = getConfigField(config, fieldName);
    %assignin('caller', fieldStrArr{iField}, value);
    try value = value{1}; catch, end
    if ~ischar(value)
        value = num2str(value);
    else
        value = ['''' value ''''];
    end
    eval([fieldName '=' value ';']);
end
    
end % function
    
    